# This is a basic workflow to help you get started with Actions

name: update

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # update weekly on sunday at 00:00
    - cron:  '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: python
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.7
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip pandas
          python -m pip install --upgrade pip requests

      - name: Set Credientials / Update Datasets
        env: # Or as an environment variable
          EMAIL: ${{ secrets.EMAIL }}
          PASS: ${{ secrets.PASS }}
        run: |
          python3 peloton-scraper/__init__.py
          
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
